[tools]
erlang = "28.3.1"
gleam = "1.14.0"

[env]
_.path = "./node_modules/.bin"
FOO = "123"

[settings]
env_file = ""
color = false

[tasks]
build = { run = "gleam build", description = "Run gleam build" }
thing = "echo $FOO"
